image: debian:bookworm

stages:          # List of stages for jobs, and their order of execution
  - build
  - release

build-linux:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - apt-get update && apt-get install -y clang-15
    - echo "Compiling the code... [linux]"
    - clang-15 src/lump.c src/lodepng.c src/main.c src/cJSON.c -o NeptuneFM -lm -target x86_64-pc-linux-gnu
    - echo "Compile complete."
  artifacts:
    name: "NeptuneFM-linux"
    paths:
      - NeptuneFM
      - "./Advanced templates"
      - "./Basic templates"
      - PLAYPAL.lmp
      - readme.txt
    untracked: false
    when: on_success
    access: all

build-windows:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - apt-get update && apt-get install -y clang-15 mingw-w64
    - echo "Compiling the code... [windows]"
    - clang-15 src/lump.c src/lodepng.c src/main.c src/cJSON.c -o NeptuneFM.exe -lm --target=x86_64-w64-mingw32 --sysroot=/usr/x86_64-w64-mingw32 -L/usr/lib/gcc/x86_64-w64-mingw32/12-win32 -lgcc -lgcc_eh
    - echo "Compile complete."
  artifacts:
    name: "NeptuneFM-windows"
    paths:
      - NeptuneFM.exe
      - "./Advanced templates"
      - "./Basic templates"
      - PLAYPAL.lmp
      - readme.txt
    untracked: false
    when: on_success
    access: all

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "Running the release job."
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    name: 'NeptuneFM nightly (?) r$CI_PIPELINE_IID'
    tag_name: 'r$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'Public download of NeptuneFM based on latest commit in main. The cutting edge. Beware of bugs!'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.
    assets:
      links:
        - name: 'NeptuneFM-windows.zip'
          url: '$CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/artifacts/r$CI_PIPELINE_IID/download?job=build-windows'
        - name: 'NeptuneFM-linux.zip'
          url: '$CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/artifacts/r$CI_PIPELINE_IID/download?job=build-linux'
